AWSTemplateFormatVersion: "2010-09-09"
Description: Client CICD

# Params
Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub Owner Name
  Repo:
    Type: String
    Description: GitHub Repo
  Branch:
    Type: String
    Description: GitHub Branch
    Default: master
  Token:
    Type: String
    Description: GitHub OAuth Token

Resources:
  DeployBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html  

  BuildArtifactsBucket:
    Type: "AWS::S3::Bucket"

  BuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub Client-CICD-BuildRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
                - codebuild.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: FAWSTrackerDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudwatch:*'
                  - 's3:*'
                  - 'sns:*'
                  - 'cloudformation:*'
                  - 'sqs:*'
                  - 'iam:PassRole'
                  - 'logs:*'
                  - 'codebuild:*'
                  - 'dynamodb:*'
                  - 'events:*'
                  - 'lambda:*'
                  - "iam:*"
                  - "codepipeline:*"
                Resource: '*'

  BuildPipeLine:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Location: !Ref BuildArtifactsBucket
        Type: S3
      RoleArn: !GetAtt BuildRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref Repo
                Branch: !Ref Branch
                OAuthToken: !Ref Token
              RunOrder: 1
        - Name: Build-Deploy
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuiltOutput
              Configuration:
                ProjectName: !Ref BuildProject
              RunOrder: 1

  BuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: Client-CICD-Build-Project
      Description: Build project for client CICD
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/nodejs:6.3.1'
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUCKET
            Value: !Ref DeployBucket
      ServiceRole: !Ref BuildRole

Outputs:
  WebsiteUrl:
    Value: !GetAtt DeployBucket.WebsiteURL
    Export:
      Name: "Pipeline::WebsiteUrl"